version: "3.9"

networks:
  network-local:
    name: network-local

services:
  nginx:
    build:
        context: .
        dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - '${NGINX_HTTP_PORT}:80'
      - '${NGINX_HTTPS_PORT}:443'
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - network-local

  php:
    build:
      context: .
    container_name: php
    ports:
      ["9000:9000", "9003:9003"]
    expose:
      ["9000", "9003"]
    volumes:
      - ./src:/var/www/html
    networks:
      - network-local

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - network-local

  postgres:
    image: postgres:15
    container_name: pgsql
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - network-local

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - network-local

  npm:
    image: node:lts-alpine
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    ports:
      - "5173:5173"
    expose:
      - "5173"
    networks:
      - network-local